version: '3.10'

services:
  db2:
    image: ibmcom/db2
    privileged: true
    ports:
      - 50000:50000
    env_file:
      - ./.env
    volumes:
      - ./database:/database
    command: db2start

    
