version: '3.10'

services:
  app:
    build: ./
    #PRODUCTION
    # command: pipenv run gunicorn LERT.wsgi:app
    #DEVELOPMENT
    command: pipenv run python ./LERT/prueba.py
    volumes: 
      - ./:/var/data
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db2
  db2:
    image: ibmcom/db2
    privileged: true
    ports:
      - 50000:50000
    env_file:
      - ./.env
    volumes:
      - ./database:/database

volumes:
  database: