version: '3.10'

services:
  db2:
    image: ibmcom/db2
    privileged: true
    ports:
      - 50000:50000
    
    env_file:
      - ./.env
      
    command: db2start
  
    volumes:
      - ./database:/database
      - /Docker:/database

    
