name: Deploy to Cloud Foundry
on:
  pull_request:
    branches: [dev]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jhunt/cf-push@v1
        with:
          api:      http://api.us-south.cf.cloud.ibm.com
          space:    Development
          org:      ${{ secrets.CF_ORG }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest.yml
          validate: false
      - uses: matt-ball/newman-action@master
        with:
          collection: postman_collection.json
          environment: postman_environment.json
      
