name: Deploy to Cloud Foundry
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jhunt/cf-push@v1
        with:
          api:      http://api.us-south.cf.cloud.ibm.com
          org:      a01733983@tec.mx
          space:    dev
          username: ${{ secrets.CF_USER }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest.yml
          validate: false
