name: Deploy to Cloud Foundry
on:
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jhunt/cf-push@v1
        with:
          api:      http://api.us-south.cf.cloud.ibm.com
          space:    Production
          org:      ${{ secrets.CF_ORG }}
          username: ${{ secrets.CF_USER }}
          password: ${{ secrets.CF_PASSWORD }}
          manifest: manifest.yml
          validate: false
